image: node:10.14.0

cache:
  paths:
    - node_modules/

deploy-development:
  before_script:
    - mkdir -p ~/.aws
    - echo "[default]" >> ~/.aws/config
    - echo "aws_access_key_id = AKIAIU7XN3RK6SYUCZKQ" >> ~/.aws/config
    - echo "aws_secret_access_key = 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"
    - cat ~/.aws/config
  stage: deploy
  script:
    - cat ~/.aws/config
  only:
    - dev
