

deploy-development:
  before_script:
    - mkdir -p ~/.aws
    - echo "[default]" >> ~/.aws/config
    - cat $AWS_ACCESS
    - echo "aws_access_key_id = " $AWS_ACCESS >> ~/.aws/config
    - echo "aws_secret_access_key = HIqAbYgyr5qIF92xgv5TMYnf419AUan5OFZeqpPz" >> ~/.aws/config
    - cat ~/.aws/config
  stage: deploy
  script:
    - cat ~/.aws/config
  only:
    - dev
